steps:
  # Step 1: Install Yarn
  # - name: 'node'
  #   entrypoint: 'npm'
  #   args: ['install', '-g', 'yarn']

  # Step 2: Install dependencies using Yarn
  - name: 'node'
    entrypoint: 'yarn'
    args: ['install']

  # Step 3: Run build/test steps using Yarn
  - name: 'node'
    entrypoint: 'yarn'
    args: ['generate']  # Adjust this according to your project's build script

  # Step 4: Deploy in Firebase
  - name: 'gcr.io/$PROJECT_ID/firebase'
    args: ['deploy', '--project=$PROJECT_ID', '--only=hosting']
